export const NOTIFICATION = {
    NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
    NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
    CLOSE_NOTIFICATION: 'CLOSE_NOTIFICATION',
    NOTIFICATION_TIMEOUT: 'NOTIFICATION_TIMEOUT',
}

export const PROGRESS = {
    IN_PROGRESS: 'IN_PROGRESS',
    IN_PROGRESS_DONE: 'IN_PROGRESS_DONE',
}
